/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/
module.exports = {
    RECIPE_EN_GB: {
        'shoot': 'R2 on playstation. R T on x box.',
        'fire': 'R2 on playstation. R T on x box.',
        'reload': 'square on playstation. x on xbox',
        'change clip': 'square on playstation. x on x box',
        'change magazine': 'square on playstation. x on x box',
        'change mag': 'square on playstation. x on x box',
        'pillar quartz block': 'A pillar of quartz can be obtained by placing a block of quartz on top of a block of quartz in mine craft.',
        'firework rocket': 'A firework rocket can be crafted by placing a firework star in the left middle square, a piece of paper in the center square, and gunpowder in the right middle square in a crafting table. Similar to a firework star, ' +
        'a firework rocket can have more gunpowder added in the bottom row to increase the duration of a rocket.',
        'rabbit stew': 'Rabbit stew can be crafted by placing cooked rabbit in the top middle square, a carrot in the middle left square, a baked potato in the center square, any type of mushroom in the middle right square, ' +
        'and a bowl in the bottom middle square.',
        'cauldron': 'A cauldron can be created by placing iron ingots in all squares but the top middle and very center squares in a crafting table.',
        'stone shovel': 'All types of shovels can be crafted by placing the desired material in the top middle square, and then sticks in the two squares directly beneath that in a crafting table.',
        'red carpet': 'Any type of carpet can be crafted by placing two wool, of the same color, next to each other in a crafting window.',
        'book and quill': 'A book and quill can be crafted by placing a book in the middle left square, an ink sac in the very center square, and a feather in the bottom middle square in a crafting table.',
        'item frame': 'An item frame can be crafted by placing leather in the very center square, and eight sticks surrounding it.',
        'map': 'A map can be crafted by placing a compass in the middle square and eight pieces of paper surrounding it.',
        'sticky piston': 'A sticky piston can be crafted by placing a slime ball on top of a piston in a crafting window',
        'bread': 'Bread can be crafted by placing three wheat across a row in a crafting table.',
        'wooden pick ax': 'All types of pick axs can be crafted by placing three of the desired material across the top row, and then placing sticks in the center and bottom middle squares in a crafting table.',
        'shears': 'Shears can be crafted by placing two Iron Ingots diagonal from each other.',
        'raw beef': 'Raw Beef will drop from the death of a Cow or Moo shrooms.',
        'smooth red sandstone': 'Smooth red sandstone can be crafted by placing four red sandstone in a two by two grid in a crafting window.',
        'prismarine crystals': 'Prismarine Crystals can be obtained by defeating Guardians and Elder Guardians.',
        'oak wood slab': 'All types of slabs can be crafted by placing three of the desired materials across a row in a crafting table.',
        'wooden sword': 'All types of swords can be crafted by placing the desired material in the top middle and very center square, with a stick beneath them, in a crafting table',
        'stairs': 'All types of stairs can be crafted by placing the desired material in all squares but the top middle, top right, and middle right squares in a crafting table.',
        'jungle fence': 'Any type of fence can be crafted by putting a wooden plank, a stick, and then another wooden plank in the bottom two rows of a crafting table.',
        'activator rail': 'An activator rail can be crafted by placing a red stone torch in the very center square, sticks above and beneath it, and then six iron ingots in the remaining squares in a crafting table.',
        'farmland': 'Farmland can be created by plowing the land with a hoe.',
        'gold ore': 'Gold ore can be obtained by breaking gold ore blocks with an iron pick ax or better',
        'andesite': 'Andesite can be mined with a pick ax or crafted by placing diorite next to cobblestone in a crafting table.',
        'rose red': 'Rose red can be crafted by placing a poppy into a crafting table.',
        'iron axe': 'All types of axes can be crafted by placing three of the desired material in the top left, top middle, and middle left squares, with sticks in the center and bottom middle squares in a crafting table.',
        'light blue dye': 'Light blue dye can be crafted by placing lapis lazuli next to bone meal in a crafting window.',
        'gray dye': 'Gray dye can be crafted by placing bonemeal next to an ink sac in a crafting window',
        'blue stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'iron horse armor': 'Horse Armor can be randomly found in Dungeons, Nether fortresses, Village blacksmiths, jungle temples, desert temples, and stronghold chests.',
        'red stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'brick stairs': 'All types of stairs can be crafted by placing the desired material in all squares but the top middle, top right, and middle right squares in a crafting table.',
        'golden leggings': 'All leggings are crafted by placing the desired material in all squares but the center square and bottom middle square in a crafting table.',
        'dark oak fence gate': 'Any type of fence gate can be crafted by placing a stick, a wooden plank, and then another stick across the bottom two rows in a crafting table.',
        'wither mob head': 'Mob heads can be obtained by having a charged creeper blow up the mob whose head you want to obtain.',
        'spider eye': 'A spider eye is randomly dropped by killing spiders or witches.',
        'magenta stained glass': 'Any type of stained glass can be crafted by placing the desired color dye in the center square, and glass surrounding that.',
        'brown stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'pumpkin pie': 'A pumpkin pie can be crafted by placing a pumpkin in the left middle square, sugar in the very center square, and an egg in the bottom middle square in a crafting table.',
        'snowball': 'A snowball can be obtained by breaking snow with a shovel.',
        'juke box': 'A juke box is crafted by placing a diamond in the very center square and wood planks all around that in a crafting table',
        'sand': 'Sand can be obtained by breaking sand blocks.',
        'dead bush': 'Dead bushes, also known as shrubs, can be obtained with shears.',
        'brick slab': 'A brick slab can be crafted by placing three brick blocks in a row in a crafting table.',
        'lily pad': 'Lily pads can be found naturally on water in swamplands or underground lakes.',
        'leather pants': 'All leggings are crafted by placing the desired material in all squares but the center square and bottom middle square in a crafting table.',
        'mossy cobblestone wall': 'A mossy cobblestone wall is crafted by placing six mossy cobblestone across the bottom two rows in a crafting table.',
        'eleven disc': "A random music disc has a possibility of dropping when a Skeleton's Arrow kills a Creeper. Alternately, music disc are found in eight percent of dungeon chests.",
        'purple stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'magenta stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'mall disc': "A random music disc has a possibility of dropping when a Skeleton's Arrow kills a Creeper. Alternately, music disc are found in eight percent of dungeon chests.",
        'jungle wood': 'All types of wood can be obtained by breaking the tree they naturally grow into.',
        'diamond ax': 'All types of axes can be crafted by placing three of the desired material in the top left, top middle, and middle left squares, with sticks in the center and bottom middle squares in a crafting table.',
        'empty map': 'A map can be crafted by placing a compass in the middle square and eight pieces of paper surrounding it.',
        'stone pressure plate': 'A stone pressure plate can be crafted by placing two smooth stone, next to each other, horizontally, in a crafting window.',
        'trapdoor': 'Trapdoors can be crafted with either wooden planks or iron ingots. To craft a wooden trapdoor, place wooden planks in all spaces in the bottom two rows. ' +
        'To craft an iron trapdoor, place iron ingots in a two by two grid in a crafting table.',
        'gold boots': 'All boots are crafted by placing the desired material in the middle left, bottom left, middle right, and bottom right squares of a crafting table.',
        'stall disc': "A random music disc has a possibility of dropping when a Skeleton's Arrow kills a Creeper. Alternately, music disc are found in eight percent of dungeon chest.",
        'red stone wire': 'Redstone wire is simply red stone placed on the floor.',
        'piston': 'A piston can be crafted by placing an iron ingot in the center square, red stone in the bottom middle square, wooden planks across the top row, and cobblestone in the remaining squares.',
        'white stained glass': 'Any type of stained glass can be crafted by placing the desired color dye in the center square, and glass surrounding that.',
        'mine cart with furnace': 'A mine cart with a furnace is crafted by placing a furnace on top of a mine cart in a crafting window.',
        'sugar': 'Sugar can be obtained by placing sugar cane in a crafting window.',
        'chain mail chest plate': 'Chain mail armor can only be obtained by trading with a villager or getting a rare drop off of a mob.',
        'feather': 'Feathers can be randomly obtained by killing chickens.',
        'light blue stained glass': 'Any type of stained glass can be crafted by placing the desired color dye in the center square, and glass surrounding that.',
        'oak fence': 'Any type of fence can be crafted by putting a wooden plank, a stick, and then another wooden plank in the bottom two rows of a crafting table.',
        'stone pick ax': 'All types of pick axes can be crafted by placing three of the desired material across the top row, and then placing sticks in the center and bottom middle squares in a crafting table.',
        'pink carpet': 'Any type of carpet can be crafted by placing two wool, of the same color, next to each other in a crafting window.',
        'monster spawner': 'Monster spawners can not be obtained without cheats in mine craft.',
        'golden carrot': 'A golden carrot can be crafted by placing a carrot in the very middle square and eight gold nuggets surrounding that.',
        'stick': 'A stick can be crafted by placing a wooden plank on top of a wooden plank in a crafting window.',
    },
    RECIPE_EN_US: {
        'shoot': 'triangle on playstation. A on xbox.',
        'fire': 'R2 on playstation. R T on x box.',
        'reload': 'square on playstation.' + 'x on x box',
        'change clip': 'square on playstation.' + 'x on x box',
        'change magazine': 'square on playstation.' + 'x on x box',
        'change mag': 'square on playstation.' + 'x on x box',
        'red carpet': 'Any type of carpet can be crafted by placing two wool, of the same color, next to each other in a crafting window.',
        'book and quill': 'A book and quill can be crafted by placing a book in the middle left square, an ink sac in the very center square, and a feather in the bottom middle square in a crafting table.',
        'item frame': 'An item frame can be crafted by placing leather in the very center square, and eight sticks surrounding it.',
        'map': 'A map can be crafted by placing a compass in the middle square and eight pieces of paper surrounding it.',
        'sticky piston': 'A sticky piston can be crafted by placing a slime ball on top of a piston in a crafting window',
        'bread': 'Bread can be crafted by placing three wheat across a row in a crafting table.',
        'wooden pick ax': 'All types of pick axs can be crafted by placing three of the desired material across the top row, and then placing sticks in the center and bottom middle squares in a crafting table.',
        'shears': 'Shears can be crafted by placing two Iron Ingots diagonal from each other.',
        'raw beef': 'Raw Beef will drop from the death of a Cow or Moo shrooms.',
        'smooth red sandstone': 'Smooth red sandstone can be crafted by placing four red sandstone in a two by two grid in a crafting window.',
        'prismarine crystals': 'Prismarine Crystals can be obtained by defeating Guardians and Elder Guardians.',
        'oak wood slab': 'All types of slabs can be crafted by placing three of the desired materials across a row in a crafting table.',
        'wooden sword': 'All types of swords can be crafted by placing the desired material in the top middle and very center square, with a stick beneath them, in a crafting table',
        'stairs': 'All types of stairs can be crafted by placing the desired material in all squares but the top middle, top right, and middle right squares in a crafting table.',
        'jungle fence': 'Any type of fence can be crafted by putting a wooden plank, a stick, and then another wooden plank in the bottom two rows of a crafting table.',
        'activator rail': 'An activator rail can be crafted by placing a red stone torch in the very center square, sticks above and beneath it, and then six iron ingots in the remaining squares in a crafting table.',
        'farmland': 'Farmland can be created by plowing the land with a hoe.',
        'gold ore': 'Gold ore can be obtained by breaking gold ore blocks with an iron pick ax or better',
        'andesite': 'Andesite can be mined with a pick ax or crafted by placing diorite next to cobblestone in a crafting table.',
        'rose red': 'Rose red can be crafted by placing a poppy into a crafting table.',
        'iron axe': 'All types of axes can be crafted by placing three of the desired material in the top left, top middle, and middle left squares, with sticks in the center and bottom middle squares in a crafting table.',
        'light blue dye': 'Light blue dye can be crafted by placing lapis lazuli next to bone meal in a crafting window.',
        'gray dye': 'Gray dye can be crafted by placing bonemeal next to an ink sac in a crafting window',
        'blue stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'iron horse armor': 'Horse Armor can be randomly found in Dungeons, Nether fortresses, Village blacksmiths, jungle temples, desert temples, and stronghold chests.',
        'red stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'brick stairs': 'All types of stairs can be crafted by placing the desired material in all squares but the top middle, top right, and middle right squares in a crafting table.',
        'golden leggings': 'All leggings are crafted by placing the desired material in all squares but the center square and bottom middle square in a crafting table.',
        'dark oak fence gate': 'Any type of fence gate can be crafted by placing a stick, a wooden plank, and then another stick across the bottom two rows in a crafting table.',
        'wither mob head': 'Mob heads can be obtained by having a charged creeper blow up the mob whose head you want to obtain.',
        'spider eye': 'A spider eye is randomly dropped by killing spiders or witches.',
        'magenta stained glass': 'Any type of stained glass can be crafted by placing the desired color dye in the center square, and glass surrounding that.',
        'brown stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'pumpkin pie': 'A pumpkin pie can be crafted by placing a pumpkin in the left middle square, sugar in the very center square, and an egg in the bottom middle square in a crafting table.',
        'snowball': 'A snowball can be obtained by breaking snow with a shovel.',
        'juke box': 'A juke box is crafted by placing a diamond in the very center square and wood planks all around that in a crafting table',
        'sand': 'Sand can be obtained by breaking sand blocks.',
        'dead bush': 'Dead bushes, also known as shrubs, can be obtained with shears.',
        'brick slab': 'A brick slab can be crafted by placing three brick blocks in a row in a crafting table.',
        'lily pad': 'Lily pads can be found naturally on water in swamplands or underground lakes.',
        'leather pants': 'All leggings are crafted by placing the desired material in all squares but the center square and bottom middle square in a crafting table.',
        'mossy cobblestone wall': 'A mossy cobblestone wall is crafted by placing six mossy cobblestone across the bottom two rows in a crafting table.',
        'eleven disc': "A random music disc has a possibility of dropping when a Skeleton's Arrow kills a Creeper. Alternately, music disc are found in eight percent of dungeon chests.",
        'purple stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'magenta stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
        'mall disc': "A random music disc has a possibility of dropping when a Skeleton's Arrow kills a Creeper. Alternately, music disc are found in eight percent of dungeon chests.",
        'jungle wood': 'All types of wood can be obtained by breaking the tree they naturally grow into.',
        'diamond ax': 'All types of axes can be crafted by placing three of the desired material in the top left, top middle, and middle left squares, with sticks in the center and bottom middle squares in a crafting table.',
        'empty map': 'A map can be crafted by placing a compass in the middle square and eight pieces of paper surrounding it.',
        'stone pressure plate': 'A stone pressure plate can be crafted by placing two smooth stone, next to each other, horizontally, in a crafting window.',
        'trapdoor': 'Trapdoors can be crafted with either wooden planks or iron ingots. To craft a wooden trapdoor, place wooden planks in all spaces in the bottom two rows. To craft an iron trapdoor, ' +
        'place iron ingots in a two by two grid in a crafting table.',
        'gold boots': 'All boots are crafted by placing the desired material in the middle left, bottom left, middle right, and bottom right squares of a crafting table.',
        'stall disc': "A random music disc has a possibility of dropping when a Skeleton's Arrow kills a Creeper. Alternately, music disc are found in eight percent of dungeon chest.",
        'red stone wire': 'Redstone wire is simply red stone placed on the floor.',
        'piston': 'A piston can be crafted by placing an iron ingot in the center square, red stone in the bottom middle square, wooden planks across the top row, and cobblestone in the remaining squares.',
        'white stained glass': 'Any type of stained glass can be crafted by placing the desired color dye in the center square, and glass surrounding that.',
        'mine cart with furnace': 'A mine cart with a furnace is crafted by placing a furnace on top of a mine cart in a crafting window.',
        'sugar': 'Sugar can be obtained by placing sugar cane in a crafting window.',
        'chain mail chest plate': 'Chain mail armor can only be obtained by trading with a villager or getting a rare drop off of a mob.',
        'feather': 'Feathers can be randomly obtained by killing chickens.',
        'light blue stained glass': 'Any type of stained glass can be crafted by placing the desired color dye in the center square, and glass surrounding that.',
        'oak fence': 'Any type of fence can be crafted by putting a wooden plank, a stick, and then another wooden plank in the bottom two rows of a crafting table.',
        'stone pick ax': 'All types of pick axes can be crafted by placing three of the desired material across the top row, and then placing sticks in the center and bottom middle squares in a crafting table.',
        'pink carpet': 'Any type of carpet can be crafted by placing two wool, of the same color, next to each other in a crafting window.',
        'monster spawner': 'Monster spawners can not be obtained without cheats in mine craft.',
        'golden carrot': 'A golden carrot can be crafted by placing a carrot in the very middle square and eight gold nuggets surrounding that.',
        'stick': 'A stick can be crafted by placing a wooden plank on top of a wooden plank in a crafting window.',
    },
    RECIPE_DE_DE: {
        'schneegolem': 'Ein Schneegolem kann erschaffen werden, indem ein Kürbis auf zwei auf dem Boden stehende Schneeblöcke gesetzt wird.',
        'quarzsäule': 'Eine Quarzsäule erhält man, indem in Minecraft ein Quarzblock auf einem Quarzblock platziert wird.',
        'feuerwerksrakete': 'Eine Feuerwerksrakete kann gecraftet werden, indem ein Feuerwerksstern in das linke mittlere Feld, ein Blatt Papier in das mittlere Feld und Schwarzpulver in das rechte mittlere Feld der Werkbank gelegt wird. ' +
        'Ähnlich wie bei einem Feuerwerksstern kann einer Feuerwerksrakete in der unteren Reihe zusätzliches Schwarzpulver hinzugefügt werden, um die Dauer der Rakete zu verlängern.',
        'kaninchenragout': 'Kaninchenragout kann gecraftet werden, indem ein Gekochtes Kaninchen in das obere mittlere Feld, eine Karotte in das linke mittlere Feld, eine Ofenkartoffel in das Feld ganz in der Mitte, ' +
        'eine beliebige Pilzart in das rechte mittlere Feld und eine Schüssel in des untere mittlere Feld platziert wird.',
        'kessel': 'Ein Kessel kann hergestellt werden, indem Eisenbarren in alle Felder der Werkbank mit Ausnahme des oberen mittleren Feldes und des Feldes ganz in der Mitte gelegt werden.',
        'steinschaufel': 'Jede Art von Schaufel lässt sich craften, indem auf der Werkbank das gewünschte Material in das obere mittlere Feld gelegt wird und dann Stöcke in die beiden direkt darunter befindlichen Felder platziert werden.',
        'roter teppich': 'Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.',
        'buch und feder': 'Buch und Feder kann gecraftet werden, indem in der Werkbank ein Buch in das linke mittlere Feld, ein Tintenbeutel in das Feld ganz in der Mitte und eine Feder in das untere mittlere Feld platziert werden.',
        'rahmen': 'Ein Rahmen kann gecraftet werden, indem Leder in das Feld ganz in der Mitte platziert und dann von acht Stöcken umgeben wird.',
        'karte': 'Eine Karte kann gecraftet werden, indem ein Kompass in das Feld ganz in der Mitte platziert und dann von acht Blättern Papier umgeben wird.',
        'klebriger Kolben': 'Ein klebriger Kolben kann gecraftet werden, indem ein Schleimball im Craftingfeld über einem Kolben platziert wird.',
        'brot': 'Brot kann gecraftet werden, indem eine Reihe der Werkbank vollständig mit Weizen gefüllt wird.',
        'holzspitzhacke': 'Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in ' +
        'der Mitte und das in der Mitte der unteren Reihe platziert wird.',
        'schere': 'Eine Schere kann gecraftet werden, indem zwei Eisenbarren diagonal zueinander platziert werden.',
        'rohes rindfleisch': 'Rohes Rindfleisch wird beim Tod einer Kuh oder Mooshroom gedroppt.',
        'glatter roter sandstein': 'Glatter roter Sandstein kann gecraftet werden, indem im Craftingfeld vier rote Sandsteinblöcke in einem 2x2-Raster platziert werden.',
        'prismarinkristalle': 'Prismarinkristalle erhält man, indem Wächter und große Wächter besiegt werden.',
        'eichenholzstufe': 'Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.',
        'holzschwert': 'Jede Art von Schwert lässt sich craften, indem auf einer Werkbank das gewünschte Material in das obere mittlere Feld sowie das Feld ganz in der Mitte platziert und dann ein Stock in das darunter befindliche Feld gelegt wird.',
        'treppe': 'Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.',
        'tropenholzzaun': 'Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.',
        'aktivierungsschiene': 'Eine Aktivierungsschiene kann gecraftet werden, indem eine Redstone-Fackel in das Feld ganz in der Mitte, Stöcke darüber und darunter und dann sechs Eisenbarren in den übrigen Feldern der Werkbank platziert werden.',
        'ackerboden': 'Ackerboden kann hergestellt werden, indem der Boden mit einer Hacke bearbeitet wird.',
        'golderz': 'Golderz erhält man, indem Golderzblöcke mit einer Spitzhacke aus Eisen oder einem hochwertigerem Material abgebaut werden.',
        'andesit': 'Andesit kann mit einer Spitzhacke abgebaut werden, oder es lässt sich craften, indem in der Werkbank Diorit neben Bruchstein platziert wird.',
        'roter farbstoff': 'Roter Farbstoff kann gecraftet werden, indem eine Mohnblume in die Werkbank gelegt wird.',
        'eisenaxt': 'Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein ' +
        'Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.',
        'hellblauer farbstoff': 'Hellblauer Farbstoff kann gecraftet werden, indem im Craftingfeld Lapislazuli neben Knochenmehl platziert wird.',
        'grauer farbstoff': 'Grauer Farbstoff kann gecraftet werden, indem im Craftingfeld Knochenmehl neben einem Tintenbeutel platziert wird.',
        'blau gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'eiserne pferderüstung': 'Eine Pferderüstung kann zufällig in Verliesen, Netherfestungen, bei Schmieden, in Dschungeltempeln, Wüstentempeln und Truhen in Festungen gefunden werden.',
        'rot gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'ziegeltreppe': 'Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.',
        'goldene hose': 'Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.',
        'schwarzeichenzauntor': 'Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.',
        'witherschädel': 'Schädel erhält man, indem man mit einem geladenen Creeper die Kreatur explodieren lässt, deren Schädel man möchte.',
        'spinnenauge': 'Ein Spinnenauge droppt zufällig beim Töten von Spinnen oder Hexen.',
        'magenta gefärbtes glas': 'Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.',
        'braun gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'kürbiskuchen': 'Ein Kürbiskuchen kann gecraftet werden, indem in der Werkbank ein Kürbis in das linke mittlere Feld, Zucker in das Feld ganz in der Mitte und ein Ei in das untere mittlere Feld platziert werden.',
        'schneeball': 'Einen Schneeball erhält man, indem Schnee mit einer Schaufel zerkleinert wird.',
        'jukebox': 'Eine Jukebox wird hergestellt, indem ein Diamant in einer Werkbank im mittleren Feld platziert und von Holzbrettern umgeben wird.',
        'sand': 'Sand erhält man, indem Sandblöcke zerkleinert werden.',
        'toter busch': 'Tote Büsche, auch nur Büsche genannt, werden mit einer Schere erhalten.',
        'ziegelstufe': 'Eine Ziegelstufe kann hergestellt werden, indem in einer Werkbank drei Ziegelstein-Blöcke in einer Reihe platziert werden.',
        'seerosenblatt': 'Seerosenblätter kommen natürlich auf Wasser in Sümpfen oder unterirdischen Seen vor.',
        'lederhose': 'Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.',
        'bemooste bruchsteinmauer': 'Eine Bemooste Bruchsteinmauer wird gecraftet, indem sechs Bemooste Bruchsteine in die beiden unteren Reihen einer Werkbank platziert werden.',
        'schallplatte 11': 'Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.',
        'violett gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'magenta gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'schallplatte mall': 'Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.',
        'tropenholz': 'Alle Holzarten können erhalten werden, indem der entsprechende Baum zerstört wird.',
        'diamantaxt': 'Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein Stock in das Feld ganz in ' +
        'der Mitte und das in der Mitte der unteren Reihe platziert werden.',
        'leere karte': 'Eine Karte kann gecraftet werden, indem ein Kompass in das Feld ganz in der Mitte platziert und dann von acht Blättern Papier umgeben wird.',
        'steindruckplatte': 'Eine Steindruckplatte lässt sich craften, indem zwei glatte Steine horizontal nebeneinander in das Craftingfeld gelegt werden.',
        'falltür': 'Falltüren können entweder mit Holzbrettern oder Eisenbarren gecraftet werden. Um eine Holzfalltür zu craften, werden Holzbretter in alle Felder der beiden unteren Reihen platziert. Um eine Eisenfalltür zu craften, ' +
        'werden Eisenbarren in einem 2x2-Raster in einer Werkbank platziert.',
        'goldstiefel': 'Alle Stiefel lassen sich craften, indem das gewünschte Material im linken mittleren, linken unteren, rechten mittleren und rechten unteren Feld einer Werkbank platziert wird.',
        'schallplatte stall': 'Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.',
        'redstone-kabel': 'Das Redstone-Kabel ist einfach Redstone, das auf dem Boden platziert wird.',
        'kolben': 'Ein Kolben kann gecraftet werden, indem ein Eisenbarren im Feld ganz in der Mitte, Redstone im unteren mittleren Feld, Holzbretter in allen Felder der oberen Reihe und Bruchstein in den übrigen Feldern platziert werden.',
        'weiß gefärbtes glas': 'Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.',
        'antriebslore': 'Eine Antriebslore wird gecraftet, indem ein Ofen in einem Craftingfeld über einer Lore platziert wird.',
        'zucker': 'Zucker kann erhalten werden, indem Zuckerrohr in einer Werkbank platziert wird.',
        'kettenhemd': 'Kettenrüstung kann nur durch den Handel mit einem Dorfbewohner oder einem seltenen Drop von einer Kreatur erhalten werden.',
        'feder': 'Federn können zufällig durch das Töten von Hühnern erhalten werden.',
        'hellblau gefärbtes glas': 'Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.',
        'eichenholzzaun': 'Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.',
        'steinspitzhacke': 'Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in ' +
        'der Mitte und das in der Mitte der unteren Reihe platziert wird.',
        'rosa teppich': 'Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.',
        'monsterspawner': 'Monsterspawner können in Minecraft nur durch Cheats erhalten werden.',
        'goldene karotte': 'Eine Goldene Karotte kann gecraftet werden, indem eine Karotte in das Feld ganz in der Mitte gelegt und dann von acht Goldklumpen umgeben wird.',
        'stock': 'Ein Stock kann gecraftet werden, indem in einem Craftingfeld ein Holzbrett über einem Holzbrett platziert wird.',
    },
};
