/* eslint-disable  func-names */
/* eslint quote-props: [""error"", ""consistent""]*/
module.exports = {
    RECIPE_EN_GB: {
        "aim": "L2 on playstation. LT on x box",
        "cross hair": "L2 on playstation. LT on x box",
        "focus": "L2 on playstation. LT on x box",
        "aim down sight": "L2 on playstation. LT on x box",
        "aim down sights": "L2 on playstation. LT on x box",
        "camera control": "Right stick on playstation. Right stick on x box",
        "camera": "Right stick on playstation. Right stick on x box",
        "rotate camera": "Right stick on playstation. Right stick on x box",
        "rotate": "Right stick on playstation. Right stick on x box",
        "look": "Right stick on playstation. Right stick on x box",
        "crouch": "Circle on playstation. B on x box",
        "knees": "Circle on playstation. B on x box",
        "dance emote": "Right on D pad on playstation. Right on D pad on x box",
        "dance": "Right on D pad on playstation. Right on D pad on x box",
        "fire weapon": "R2 on playstation. RT on x box",
        "fire": "R2 on playstation. RT on x box",
        "shoot": "R2 on playstation. RT on x box",
        "shoot weapon": "R2 on playstation. RT on x box",
        "fire weapon": "R2 on playstation. RT on x box",
        "throw grenade": "L1 on playstation. LB on x box",
        "grenade": "L1 on playstation. LB on x box",
        "bomb": "L1 on playstation. LB on x box",
        "nade": "L1 on playstation. LB on x box",
        "throw grenade": "L1 on playstation. LB on x box",
        "jump": "X on playstation. A on x box",
        "vault": "X on playstation. A on x box",
        "engage": "R3 on playstation. Right Stick Button on x box",
        "spot": "R3 on playstation. Right Stick Button on x box",
        "mark": "R3 on playstation. Right Stick Button on x box",
        "spot enemy": "R3 on playstation. Right Stick Button on x box",
        "mark enemy": "R3 on playstation. Right Stick Button on x box",
        "highlight enemy": "R3 on playstation. Right Stick Button on x box",
        "marker": "R3 on playstation. Right Stick Button on x box",
        "order": "R3 on playstation. Right Stick Button on x box",
        "direct": "R3 on playstation. Right Stick Button on x box",
        "highlight": "R3 on playstation. Right Stick Button on x box",
        "highlight player": "R3 on playstation. Right Stick Button on x box",
        "melee": "R1 on playstation. RB on x box",
        "knife": "R1 on playstation. RB on x box",
        "perform melee attack": "R1 on playstation. RB on x box",
        "game menu": "Start or options on playstation. Start button on x box",
        "menu": "Start or options on playstation. Start button on x box",
        "opens menu": "Start or options on playstation. Start button on x box",
        "move": "Left stick on playstation. Left stick on x box",
        "point emote": "Left on D pad on playstation. Left on D pad on x box",
        "point": "Left on D pad on playstation. Left on D pad on x box",
        "reload": "Square on playstation. X on x box",
        "change clip": "Square on playstation. X on x box",
        "change magazine": "Square on playstation. X on x box",
        "change mag": "Square on playstation. X on x box",
        "reload weapon": "Square on playstation. X on x box",
        "sit emote": "Down on D pad on playstation. Down on D pad on x box",
        "sit": "Down on D pad on playstation. Down on D pad on x box",
        "slide": "Circle while sprinting on playstation. B while sprinting on x box",
        "triggers super ability": "L1 and R1 together on playstation. LB and RB together on x box",
        "sprint": "L3 on playstation. Left Stick Button on x box",
        "run": "L3 on playstation. Left Stick Button on x box",
        "summon ghost": "Select or toucpad on playstation. Back button on x box",
        "ghost": "Select or toucpad on playstation. Back button on x box",
        "switch to heavy weapon": "Hold triangle on playstation. Hold Y on x box",
        "heavy weapon": "Hold triangle on playstation. Hold Y on x box",
        "switch weapon": "Triangle on playstation. Y on x box",
        "switch weapons": "Triangle on playstation. Y on x box",
        "wave emote": "Up on D pad on playstation. Up on D pad on x box",
        "wave": "Up on D pad on playstation. Up on D pad on x box",
    },
    RECIPE_EN_US: {
        "aim": "L2 on playstation. LT on x box",
        "cross hair": "L2 on playstation. LT on x box",
        "focus": "L2 on playstation. LT on x box",
        "aim down sight": "L2 on playstation. LT on x box",
        "aim down sights": "L2 on playstation. LT on x box",
        "camera control": "Right stick on playstation. Right stick on x box",
        "camera": "Right stick on playstation. Right stick on x box",
        "rotate camera": "Right stick on playstation. Right stick on x box",
        "rotate": "Right stick on playstation. Right stick on x box",
        "look": "Right stick on playstation. Right stick on x box",
        "crouch": "Circle on playstation. B on x box",
        "knees": "Circle on playstation. B on x box",
        "dance emote": "Right on D pad on playstation. Right on D pad on x box",
        "dance": "Right on D pad on playstation. Right on D pad on x box",
        "fire weapon": "R2 on playstation. RT on x box",
        "fire": "R2 on playstation. RT on x box",
        "shoot": "R2 on playstation. RT on x box",
        "shoot weapon": "R2 on playstation. RT on x box",
        "fire weapon": "R2 on playstation. RT on x box",
        "throw grenade": "L1 on playstation. LB on x box",
        "grenade": "L1 on playstation. LB on x box",
        "bomb": "L1 on playstation. LB on x box",
        "nade": "L1 on playstation. LB on x box",
        "throw grenade": "L1 on playstation. LB on x box",
        "jump": "X on playstation. A on x box",
        "vault": "X on playstation. A on x box",
        "engage": "R3 on playstation. Right Stick Button on x box",
        "spot": "R3 on playstation. Right Stick Button on x box",
        "mark": "R3 on playstation. Right Stick Button on x box",
        "spot enemy": "R3 on playstation. Right Stick Button on x box",
        "mark enemy": "R3 on playstation. Right Stick Button on x box",
        "highlight enemy": "R3 on playstation. Right Stick Button on x box",
        "marker": "R3 on playstation. Right Stick Button on x box",
        "order": "R3 on playstation. Right Stick Button on x box",
        "direct": "R3 on playstation. Right Stick Button on x box",
        "highlight": "R3 on playstation. Right Stick Button on x box",
        "highlight player": "R3 on playstation. Right Stick Button on x box",
        "melee": "R1 on playstation. RB on x box",
        "knife": "R1 on playstation. RB on x box",
        "perform melee attack": "R1 on playstation. RB on x box",
        "game menu": "Start or options on playstation. Start button on x box",
        "menu": "Start or options on playstation. Start button on x box",
        "opens menu": "Start or options on playstation. Start button on x box",
        "move": "Left stick on playstation. Left stick on x box",
        "point emote": "Left on D pad on playstation. Left on D pad on x box",
        "point": "Left on D pad on playstation. Left on D pad on x box",
        "reload": "Square on playstation. X on x box",
        "change clip": "Square on playstation. X on x box",
        "change magazine": "Square on playstation. X on x box",
        "change mag": "Square on playstation. X on x box",
        "reload weapon": "Square on playstation. X on x box",
        "sit emote": "Down on D pad on playstation. Down on D pad on x box",
        "sit": "Down on D pad on playstation. Down on D pad on x box",
        "slide": "Circle while sprinting on playstation. B while sprinting on x box",
        "triggers super ability": "L1 and R1 together on playstation. LB and RB together on x box",
        "sprint": "L3 on playstation. Left Stick Button on x box",
        "run": "L3 on playstation. Left Stick Button on x box",
        "summon ghost": "Select or toucpad on playstation. Back button on x box",
        "ghost": "Select or toucpad on playstation. Back button on x box",
        "switch to heavy weapon": "Hold triangle on playstation. Hold Y on x box",
        "heavy weapon": "Hold triangle on playstation. Hold Y on x box",
        "switch weapon": "Triangle on playstation. Y on x box",
        "switch weapons": "Triangle on playstation. Y on x box",
        "wave emote": "Up on D pad on playstation. Up on D pad on x box",
        "wave": "Up on D pad on playstation. Up on D pad on x box",
    },
};