/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/
module.exports = {
    RECIPE_EN_GB: {
        'wall jump': 'Triangle on playstation. Y on x box',
        'wall creep': 'R1 on playstation. RB on x box',
        'wall charge': 'X on playstation. X on x box',
        'volley': 'Circle on playstation. B on x box',
        'toggle camera target': 'Track Pad or Select Button on playstation. Back button on x box',
        'throw': 'X on playstation. X on x box',
        'through ball': 'Triangle on playstation. Y on x box',
        'threaded through pass': 'R1 + Triangle on playstation. RB + Y on x box',
        'third kick taker run over ball': 'R1 + Circle then X on playstation. RB + B then X on x box',
        'third kick taker curled shot': 'R1 + Circle on playstation. RB + B on x box',
        'third kick taker': 'R1 on playstation. RB on x box',
        'teammate contain': 'R1, Press and Hold on playstation. RB, Press and Hold on x box',
        'team press': 'On D-Pad: UP then DOWN on playstation. On D-Pad: UP then DOWN on x box',
        'tackle': 'Circle or Hold L2 on playstation. B or hold LT on x box',
        'switch to goalkeeper': 'Track Pad or Select Button on playstation. Back button on x box',
        'change to goalkeeper': 'Track Pad or Select Button on playstation. Back button on x box',
        'switch player': 'right stick + direction on playstation. right stick + direction on x box',
        'manual switch player': 'right stick + direction on playstation. right stick + direction on x box',
        'swap wings': 'On D-Pad: UP then LEFT on playstation. On D-Pad: UP then LEFT on x box',
        'suggest through balll': 'Triangle on playstation. Y on x box',
        'suggest shot': 'Circle on playstation. B on x box',
        'suggest cross': 'Sqaure on playstation. X on x box',
        'stutter': 'L2 on playstation. LT on x box',
        'stop ball': 'R2 + no direction on playstation. RT + no direction on x box',
        'stop and face goal': 'L1 + no direction on playstation. LB + no direction on x box',
        'sprint': 'R2 on playstation. RT on x box',
        'slow movement facing ball': 'L2 + left stick on playstation. LT + left stick on x box',
        'slow dribble': 'L2 + direction on playstation. LT + direction on x box',
        'sliding tackle': 'Square on playstation. X on x box',
        'skills': 'right stick on playstation. right stick on x box',
        'skill moves': 'right stick on playstation. right stick on x box',
        'tricks': 'right stick on playstation. right stick on x box',
        'trick shots': 'right stick on playstation. right stick on x box',
        'shot power': 'Circle on playstation. B on x box',
        'short throw in': 'Triangle or X on playstation. Y or X on x box',
        'short pass': 'X on playstation. X on x box',
        'short header': 'X on playstation. X on x box',
        'shoot': 'Circle on playstation. B on x box',
        'select kick taker': 'R2 on playstation. RT on x box',
        'pick kick taker': 'R2 on playstation. RT on x box',
        'choose kick taker': 'R2 on playstation. RT on x box',
        'select kicker': 'R2 on playstation. RT on x box',
        'pick kicker': 'R2 on playstation. RT on x box',
        'choose kicker': 'R2 on playstation. RT on x box',
        'second kick taker run over ball': 'L2 + Circle then X on playstation. LT + B then X on x box',
        'second kick taker layoff pass': 'L2 + X on playstation. LT + X on x box',
        'second kick taker layoff chip': 'L2 + Square on playstation. LT + X on x box',
        'second kick taker curled shot': 'L2 + Circle on playstation. LT + B on x box',
        'second kick taker': 'L2 on playstation. LT on x box',
        'second defender contain': 'R1, Press and Hold on playstation. RB, Press and Hold on x box',
        'running jockey': 'Hold L2 + R2 on playstation. Hold LT + RT on x box',
        'run up throw': 'R1 + X on playstation. RB + X on x box',
        'run up shot': 'L1 + Circle on playstation. LB + B on x box',
        'run up kick': 'R1 + Square on playstation. RB + X on x box',
        'run out': 'Triangle, Press and Hold on playstation. Y, Press and Hold on x box',
        'quick get up (after slide tackle)': 'Square on playstation. X on x box',
        'push': 'Circle or Hold L2 on playstation. B or hold LT on x box',
        'punch': 'Triangle, Press and Hold on playstation. Y, Press and Hold on x box',
        'pull and hold (when chasing)': 'Circle, Press and Hold on playstation. B, Press and Hold on x box',
        'pull': 'Circle or Hold L2 on playstation. B or hold LT on x box',
        'protect ball': 'L2 on playstation. LT on x box',
        'protect': 'L2 + direction on playstation. LT + direction on x box',
        'pressure': 'On D-Pad: DOWN then DOWN on playstation. On D-Pad: DOWN then DOWN on x box',
        'power': 'B for free kicks. x for penalties on playstation. Circle for free kick. square for penalties on x box',
        'possession': 'On D-Pad: DOWN then LEFT on playstation. On D-Pad: DOWN then LEFT on x box',
        'pick up ball': 'R1 on playstation. RB on x box',
        'penalty aim': 'left stick on playstation. left stick on x box',
        'pass': 'X on playstation. X on x box',
        'offside trap': 'On D-Pad: UP then UP on playstation. On D-Pad: UP then UP on x box',
        'no touch small feints': 'L1 on playstation. LB on x box',
        'no touch big feints': 'L1 + L2 on playstation. LB + LT on x box',
        'movement during run up': 'left stick on playstation. left stick on x box',
        'movement along the line': 'left stick on playstation. left stick on x box',
        'move wall': 'L2 or R2 on playstation. LT or RT on x box',
        'move throw in receiver': 'L1 on playstation. LB on x box',
        'move player': 'left stick on playstation. left stick on x box',
        'move camera': 'right stick on playstation. right stick on x box',
        'mentality': 'On D-Pad: LEFT or RIGHT on playstation. On D-Pad: LEFT or RIGHT on x box',
        'manual protect': 'L1 + L2 on playstation. LB + LT on x box',
        'low shot': 'Circle + Tap Circle on playstation. B + Tap B on x box',
        'low cross': 'Square, twice on playstation. X, twice on x box',
        'long throw in': 'Square on playstation. X on x box',
        'long ball': 'On D-Pad: DOWN then RIGHT on playstation. On D-Pad: DOWN then RIGHT on x box',
        'lobbed through ball': 'L1 + Triangle on playstation. LB + Y on x box',
        'lob pass': 'Square on playstation. X on x box',
        'knock on': 'R2 + right stick + direction on playstation. RT + right stick + direction on x box',
        'kick power': 'Square on playstation. X on x box',
        'jump': 'Triangle on playstation. Y on x box',
        'jockey': 'L2 on playstation. LT on x box',
        'high pressure': 'On D-Pad: DOWN then DOWN on playstation. On D-Pad: DOWN then DOWN on x box',
        'high pass': 'Square on playstation. X on x box',
        'header': 'Circle or X or square on playstation. B or X on x box',
        'harass': 'Circle or Hold L2 on playstation. B or hold LT on x box',
        'ground pass': 'X on playstation. X on x box',
        'ground cross': 'Square, three times on playstation. X, three times on x box',
        'goalkeeper switch': 'Track Pad or Select Button on playstation. Back button on x box',
        'goalkeeper move side to side': 'left stick + direction on playstation. left stick + direction on x box',
        'move side to side': 'left stick + direction on playstation. left stick + direction on x box',
        'goalkeeper dive': 'right stick + direction on playstation. right stick + direction on x box',
        'free kick aim': 'right stick on playstation. right stick on x box',
        'flair shot': 'L2 + Circle on playstation. LT + B on x box',
        'flair pass': 'L2 + X on playstation. LT + X on x box',
        'first touch': 'R2 + right stick + direction on playstation. RT + right stick + direction on x box',
        'finesse shot': 'R1 + Circle on playstation. RB + B on x box',
        'fake throw': 'Square or circle then X plus direction on playstation. x or b then A plus direction on x box',
        'fake shot': 'Circle then X + direction on playstation. B then X + direction on x box',
        'fake pass': 'Square then X + direction on playstation. X then X + direction on x box',
        'face up dribbling': 'L2 + R2 on playstation. LT + RT on x box',
        'face goal': 'L1 + no direction on playstation. LB + no direction on x box',
        'engage shielding opponent': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'shield': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'block': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'shield player': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'block player': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'early cross': 'L1 + Square on playstation. LB + X on x box',
        'dummy throw': 'Square or circle then X plus direction on playstation. x or b then A plus direction on x box',
        'dummy shot': 'Circle then X + direction on playstation. B then X + direction on x box',
        'dummy pass': 'Square then X + direction on playstation. X then X + direction on x box',
        'dummy a pass': 'R1, Press and Hold on playstation. RB, Press and Hold on x box',
        'drop kick': 'Circle or square on playstation. B or X on x box',
        'drop ball': 'Triangle on playstation. Y on x box',
        'driven throw': 'R1 + X on playstation. RB + X on x box',
        'driven shot': 'L1 + Circle on playstation. LB + B on x box',
        'driven kick': 'R1 + Square on playstation. RB + X on x box',
        'driven ground pass': 'R1 + X on playstation. RB + X on x box',
        'downward header shot': 'Circle + Tap Circle on playstation. B + Tap B on x box',
        'downward header': 'Circle + Tap Circle on playstation. B + Tap B on x box',
        'dive at player': 'Square on playstation. X on x box',
        'dive at feet': 'Square on playstation. X on x box',
        'dive': 'Hold X + direction on playstation. Hold X + direction on x box',
        'curled shot': 'Circle on playstation. B on x box',
        'curl in': 'Circle on playstation. B on x box',
        'curl': 'Circle on playstation. B on x box',
        'cross into the box': 'Square on playstation. X on x box',
        'cross in': 'Square on playstation. X on x box',
        'cross along the ground': 'Square, three times on playstation. X, three times on x box',
        'cross': 'Square on playstation. X on x box',
        'counter attack': 'On D-Pad: DOWN then UP on playstation. On D-Pad: DOWN then UP on x box',
        'contain': 'X, Press and Hold on playstation. X, Press and Hold on x box',
        'clearance': 'Circle on playstation. B on x box',
        'clear the ball': 'Circle on playstation. B on x box',
        'clear': 'Circle on playstation. B on x box',
        'chip shot': 'L1 + Circle on playstation. LB + B on x box',
        'charge': 'Triangle, Press and Hold on playstation. Y, Press and Hold on x box',
        'change player': 'L1 on playstation. LB on x box',
        'change mentality': 'On D-Pad: LEFT or RIGHT on playstation. On D-Pad: LEFT or RIGHT on x box',
        'change kick taker': 'R1 or L2 on playstation. RB or LT on x box',
        'centre back joins attack': 'On D-Pad: UP then RIGHT on playstation. On D-Pad: UP then RIGHT on x box',
        'cancel shot': 'L2 + R2 on playstation. LT + RT on x box',
        'cancel': 'L2 + R2 on playstation. LT + RT on x box',
        'camera target': 'Track Pad or Select Button on playstation. Back button on x box',
        'call third kick taker': 'R1 on playstation. RB on x box',
        'call second kick taker': 'L2 on playstation. LT on x box',
        'call player short': 'L2 on playstation. LT on x box',
        'call for support': 'R1 on playstation. RB on x box',
        'call for or suggest pass': 'X on playstation. X on x box',
        'bring centre back up': 'On D-Pad: UP then RIGHT on playstation. On D-Pad: UP then RIGHT on x box',
        'bouncing lob pass': 'R1 + Square on playstation. RB + X on x box',
        'autopositioning': 'L1, Press and Hold on playstation. LB, Press and Hold on x box',
        'apply shot power': 'Circle on playstation. B on x box',
        'apply curl during run up': 'left stick on playstation. left stick on x box',
        'anticipation save': 'Circle on playstation. B on x box',
        'aim': 'left stick on playstation. left stick on x box',
        'adjust start position': 'left stick on playstation. left stick on x box',
        'add spin': 'Circle or left stick on playstation. B or left stick on x box',
        'add kick taker': 'R1 or L2 on playstation. RB or LT on x box',
        'add curl': 'Circle or left stick on playstation. B or left stick on x box',
    },
    RECIPE_EN_US: {
        'wall jump': 'Triangle on playstation. Y on x box',
        'wall creep': 'R1 on playstation. RB on x box',
        'wall charge': 'X on playstation. X on x box',
        'volley': 'Circle on playstation. B on x box',
        'toggle camera target': 'Track Pad or Select Button on playstation. Back button on x box',
        'throw': 'X on playstation. X on x box',
        'through ball': 'Triangle on playstation. Y on x box',
        'threaded through pass': 'R1 + Triangle on playstation. RB + Y on x box',
        'third kick taker run over ball': 'R1 + Circle then X on playstation. RB + B then X on x box',
        'third kick taker curled shot': 'R1 + Circle on playstation. RB + B on x box',
        'third kick taker': 'R1 on playstation. RB on x box',
        'teammate contain': 'R1, Press and Hold on playstation. RB, Press and Hold on x box',
        'team press': 'On D-Pad: UP then DOWN on playstation. On D-Pad: UP then DOWN on x box',
        'tackle': 'Circle or Hold L2 on playstation. B or hold LT on x box',
        'switch to goalkeeper': 'Track Pad or Select Button on playstation. Back button on x box',
        'change to goalkeeper': 'Track Pad or Select Button on playstation. Back button on x box',
        'switch player': 'right stick + direction on playstation. right stick + direction on x box',
        'manual switch player': 'right stick + direction on playstation. right stick + direction on x box',
        'swap wings': 'On D-Pad: UP then LEFT on playstation. On D-Pad: UP then LEFT on x box',
        'suggest through balll': 'Triangle on playstation. Y on x box',
        'suggest shot': 'Circle on playstation. B on x box',
        'suggest cross': 'Sqaure on playstation. X on x box',
        'stutter': 'L2 on playstation. LT on x box',
        'stop ball': 'R2 + no direction on playstation. RT + no direction on x box',
        'stop and face goal': 'L1 + no direction on playstation. LB + no direction on x box',
        'sprint': 'R2 on playstation. RT on x box',
        'slow movement facing ball': 'L2 + left stick on playstation. LT + left stick on x box',
        'slow dribble': 'L2 + direction on playstation. LT + direction on x box',
        'sliding tackle': 'Square on playstation. X on x box',
        'skills': 'right stick on playstation. right stick on x box',
        'skill moves': 'right stick on playstation. right stick on x box',
        'tricks': 'right stick on playstation. right stick on x box',
        'trick shots': 'right stick on playstation. right stick on x box',
        'shot power': 'Circle on playstation. B on x box',
        'short throw in': 'Triangle or X on playstation. Y or X on x box',
        'short pass': 'X on playstation. X on x box',
        'short header': 'X on playstation. X on x box',
        'shoot': 'Circle on playstation. B on x box',
        'select kick taker': 'R2 on playstation. RT on x box',
        'pick kick taker': 'R2 on playstation. RT on x box',
        'choose kick taker': 'R2 on playstation. RT on x box',
        'select kicker': 'R2 on playstation. RT on x box',
        'pick kicker': 'R2 on playstation. RT on x box',
        'choose kicker': 'R2 on playstation. RT on x box',
        'second kick taker run over ball': 'L2 + Circle then X on playstation. LT + B then X on x box',
        'second kick taker layoff pass': 'L2 + X on playstation. LT + X on x box',
        'second kick taker layoff chip': 'L2 + Square on playstation. LT + X on x box',
        'second kick taker curled shot': 'L2 + Circle on playstation. LT + B on x box',
        'second kick taker': 'L2 on playstation. LT on x box',
        'second defender contain': 'R1, Press and Hold on playstation. RB, Press and Hold on x box',
        'running jockey': 'Hold L2 + R2 on playstation. Hold LT + RT on x box',
        'run up throw': 'R1 + X on playstation. RB + X on x box',
        'run up shot': 'L1 + Circle on playstation. LB + B on x box',
        'run up kick': 'R1 + Square on playstation. RB + X on x box',
        'run out': 'Triangle, Press and Hold on playstation. Y, Press and Hold on x box',
        'quick get up (after slide tackle)': 'Square on playstation. X on x box',
        'push': 'Circle or Hold L2 on playstation. B or hold LT on x box',
        'punch': 'Triangle, Press and Hold on playstation. Y, Press and Hold on x box',
        'pull and hold (when chasing)': 'Circle, Press and Hold on playstation. B, Press and Hold on x box',
        'pull': 'Circle or Hold L2 on playstation. B or hold LT on x box',
        'protect ball': 'L2 on playstation. LT on x box',
        'protect': 'L2 + direction on playstation. LT + direction on x box',
        'pressure': 'On D-Pad: DOWN then DOWN on playstation. On D-Pad: DOWN then DOWN on x box',
        'power': 'B for free kicks. x for penalties on playstation. Circle for free kick. square for penalties on x box',
        'possession': 'On D-Pad: DOWN then LEFT on playstation. On D-Pad: DOWN then LEFT on x box',
        'pick up ball': 'R1 on playstation. RB on x box',
        'penalty aim': 'left stick on playstation. left stick on x box',
        'pass': 'X on playstation. X on x box',
        'offside trap': 'On D-Pad: UP then UP on playstation. On D-Pad: UP then UP on x box',
        'no touch small feints': 'L1 on playstation. LB on x box',
        'no touch big feints': 'L1 + L2 on playstation. LB + LT on x box',
        'movement during run up': 'left stick on playstation. left stick on x box',
        'movement along the line': 'left stick on playstation. left stick on x box',
        'move wall': 'L2 or R2 on playstation. LT or RT on x box',
        'move throw in receiver': 'L1 on playstation. LB on x box',
        'move player': 'left stick on playstation. left stick on x box',
        'move camera': 'right stick on playstation. right stick on x box',
        'mentality': 'On D-Pad: LEFT or RIGHT on playstation. On D-Pad: LEFT or RIGHT on x box',
        'manual protect': 'L1 + L2 on playstation. LB + LT on x box',
        'low shot': 'Circle + Tap Circle on playstation. B + Tap B on x box',
        'low cross': 'Square, twice on playstation. X, twice on x box',
        'long throw in': 'Square on playstation. X on x box',
        'long ball': 'On D-Pad: DOWN then RIGHT on playstation. On D-Pad: DOWN then RIGHT on x box',
        'lobbed through ball': 'L1 + Triangle on playstation. LB + Y on x box',
        'lob pass': 'Square on playstation. X on x box',
        'knock on': 'R2 + right stick + direction on playstation. RT + right stick + direction on x box',
        'kick power': 'Square on playstation. X on x box',
        'jump': 'Triangle on playstation. Y on x box',
        'jockey': 'L2 on playstation. LT on x box',
        'high pressure': 'On D-Pad: DOWN then DOWN on playstation. On D-Pad: DOWN then DOWN on x box',
        'high pass': 'Square on playstation. X on x box',
        'header': 'Circle or X or square on playstation. B or X on x box',
        'harass': 'Circle or Hold L2 on playstation. B or hold LT on x box',
        'ground pass': 'X on playstation. X on x box',
        'ground cross': 'Square, three times on playstation. X, three times on x box',
        'goalkeeper switch': 'Track Pad or Select Button on playstation. Back button on x box',
        'goalkeeper move side to side': 'left stick + direction on playstation. left stick + direction on x box',
        'move side to side': 'left stick + direction on playstation. left stick + direction on x box',
        'goalkeeper dive': 'right stick + direction on playstation. right stick + direction on x box',
        'free kick aim': 'right stick on playstation. right stick on x box',
        'flair shot': 'L2 + Circle on playstation. LT + B on x box',
        'flair pass': 'L2 + X on playstation. LT + X on x box',
        'first touch': 'R2 + right stick + direction on playstation. RT + right stick + direction on x box',
        'finesse shot': 'R1 + Circle on playstation. RB + B on x box',
        'fake throw': 'Square or circle then X plus direction on playstation. x or b then A plus direction on x box',
        'fake shot': 'Circle then X + direction on playstation. B then X + direction on x box',
        'fake pass': 'Square then X + direction on playstation. X then X + direction on x box',
        'face up dribbling': 'L2 + R2 on playstation. LT + RT on x box',
        'face goal': 'L1 + no direction on playstation. LB + no direction on x box',
        'engage shielding opponent': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'shield': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'block': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'shield player': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'block player': 'L2 + left stick,Towards Dribbler on playstation. LT + left stick, Towards Dribbler on x box',
        'early cross': 'L1 + Square on playstation. LB + X on x box',
        'dummy throw': 'Square or circle then X plus direction on playstation. x or b then A plus direction on x box',
        'dummy shot': 'Circle then X + direction on playstation. B then X + direction on x box',
        'dummy pass': 'Square then X + direction on playstation. X then X + direction on x box',
        'dummy a pass': 'R1, Press and Hold on playstation. RB, Press and Hold on x box',
        'drop kick': 'Circle or square on playstation. B or X on x box',
        'drop ball': 'Triangle on playstation. Y on x box',
        'driven throw': 'R1 + X on playstation. RB + X on x box',
        'driven shot': 'L1 + Circle on playstation. LB + B on x box',
        'driven kick': 'R1 + Square on playstation. RB + X on x box',
        'driven ground pass': 'R1 + X on playstation. RB + X on x box',
        'downward header shot': 'Circle + Tap Circle on playstation. B + Tap B on x box',
        'downward header': 'Circle + Tap Circle on playstation. B + Tap B on x box',
        'dive at player': 'Square on playstation. X on x box',
        'dive at feet': 'Square on playstation. X on x box',
        'dive': 'Hold X + direction on playstation. Hold X + direction on x box',
        'curled shot': 'Circle on playstation. B on x box',
        'curl in': 'Circle on playstation. B on x box',
        'curl': 'Circle on playstation. B on x box',
        'cross into the box': 'Square on playstation. X on x box',
        'cross in': 'Square on playstation. X on x box',
        'cross along the ground': 'Square, three times on playstation. X, three times on x box',
        'cross': 'Square on playstation. X on x box',
        'counter attack': 'On D-Pad: DOWN then UP on playstation. On D-Pad: DOWN then UP on x box',
        'contain': 'X, Press and Hold on playstation. X, Press and Hold on x box',
        'clearance': 'Circle on playstation. B on x box',
        'clear the ball': 'Circle on playstation. B on x box',
        'clear': 'Circle on playstation. B on x box',
        'chip shot': 'L1 + Circle on playstation. LB + B on x box',
        'charge': 'Triangle, Press and Hold on playstation. Y, Press and Hold on x box',
        'change player': 'L1 on playstation. LB on x box',
        'change mentality': 'On D-Pad: LEFT or RIGHT on playstation. On D-Pad: LEFT or RIGHT on x box',
        'change kick taker': 'R1 or L2 on playstation. RB or LT on x box',
        'centre back joins attack': 'On D-Pad: UP then RIGHT on playstation. On D-Pad: UP then RIGHT on x box',
        'cancel shot': 'L2 + R2 on playstation. LT + RT on x box',
        'cancel': 'L2 + R2 on playstation. LT + RT on x box',
        'camera target': 'Track Pad or Select Button on playstation. Back button on x box',
        'call third kick taker': 'R1 on playstation. RB on x box',
        'call second kick taker': 'L2 on playstation. LT on x box',
        'call player short': 'L2 on playstation. LT on x box',
        'call for support': 'R1 on playstation. RB on x box',
        'call for or suggest pass': 'X on playstation. X on x box',
        'bring centre back up': 'On D-Pad: UP then RIGHT on playstation. On D-Pad: UP then RIGHT on x box',
        'bouncing lob pass': 'R1 + Square on playstation. RB + X on x box',
        'autopositioning': 'L1, Press and Hold on playstation. LB, Press and Hold on x box',
        'apply shot power': 'Circle on playstation. B on x box',
        'apply curl during run up': 'left stick on playstation. left stick on x box',
        'anticipation save': 'Circle on playstation. B on x box',
        'aim': 'left stick on playstation. left stick on x box',
        'adjust start position': 'left stick on playstation. left stick on x box',
        'add spin': 'Circle or left stick on playstation. B or left stick on x box',
        'add kick taker': 'R1 or L2 on playstation. RB or LT on x box',
        'add curl': 'Circle or left stick on playstation. B or left stick on x box',
    },
    RECIPE_DE_DE: {
        'schneegolem': 'Ein Schneegolem kann erschaffen werden, indem ein Kürbis auf zwei auf dem Boden stehende Schneeblöcke gesetzt wird.',
        'quarzsäule': 'Eine Quarzsäule erhält man, indem in Minecraft ein Quarzblock auf einem Quarzblock platziert wird.',
        'feuerwerksrakete': 'Eine Feuerwerksrakete kann gecraftet werden, indem ein Feuerwerksstern in das linke mittlere Feld, ein Blatt Papier in das mittlere Feld und Schwarzpulver in das rechte mittlere Feld der Werkbank gelegt wird. ' +
        'Ähnlich wie bei einem Feuerwerksstern kann einer Feuerwerksrakete in der unteren Reihe zusätzliches Schwarzpulver hinzugefügt werden, um die Dauer der Rakete zu verlängern.',
        'kaninchenragout': 'Kaninchenragout kann gecraftet werden, indem ein Gekochtes Kaninchen in das obere mittlere Feld, eine Karotte in das linke mittlere Feld, eine Ofenkartoffel in das Feld ganz in der Mitte, ' +
        'eine beliebige Pilzart in das rechte mittlere Feld und eine Schüssel in des untere mittlere Feld platziert wird.',
        'kessel': 'Ein Kessel kann hergestellt werden, indem Eisenbarren in alle Felder der Werkbank mit Ausnahme des oberen mittleren Feldes und des Feldes ganz in der Mitte gelegt werden.',
        'steinschaufel': 'Jede Art von Schaufel lässt sich craften, indem auf der Werkbank das gewünschte Material in das obere mittlere Feld gelegt wird und dann Stöcke in die beiden direkt darunter befindlichen Felder platziert werden.',
        'roter teppich': 'Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.',
        'buch und feder': 'Buch und Feder kann gecraftet werden, indem in der Werkbank ein Buch in das linke mittlere Feld, ein Tintenbeutel in das Feld ganz in der Mitte und eine Feder in das untere mittlere Feld platziert werden.',
        'rahmen': 'Ein Rahmen kann gecraftet werden, indem Leder in das Feld ganz in der Mitte platziert und dann von acht Stöcken umgeben wird.',
        'karte': 'Eine Karte kann gecraftet werden, indem ein Kompass in das Feld ganz in der Mitte platziert und dann von acht Blättern Papier umgeben wird.',
        'klebriger Kolben': 'Ein klebriger Kolben kann gecraftet werden, indem ein Schleimball im Craftingfeld über einem Kolben platziert wird.',
        'brot': 'Brot kann gecraftet werden, indem eine Reihe der Werkbank vollständig mit Weizen gefüllt wird.',
        'holzspitzhacke': 'Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in ' +
        'der Mitte und das in der Mitte der unteren Reihe platziert wird.',
        'schere': 'Eine Schere kann gecraftet werden, indem zwei Eisenbarren diagonal zueinander platziert werden.',
        'rohes rindfleisch': 'Rohes Rindfleisch wird beim Tod einer Kuh oder Mooshroom gedroppt.',
        'glatter roter sandstein': 'Glatter roter Sandstein kann gecraftet werden, indem im Craftingfeld vier rote Sandsteinblöcke in einem 2x2-Raster platziert werden.',
        'prismarinkristalle': 'Prismarinkristalle erhält man, indem Wächter und große Wächter besiegt werden.',
        'eichenholzstufe': 'Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.',
        'holzschwert': 'Jede Art von Schwert lässt sich craften, indem auf einer Werkbank das gewünschte Material in das obere mittlere Feld sowie das Feld ganz in der Mitte platziert und dann ein Stock in das darunter befindliche Feld gelegt wird.',
        'treppe': 'Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.',
        'tropenholzzaun': 'Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.',
        'aktivierungsschiene': 'Eine Aktivierungsschiene kann gecraftet werden, indem eine Redstone-Fackel in das Feld ganz in der Mitte, Stöcke darüber und darunter und dann sechs Eisenbarren in den übrigen Feldern der Werkbank platziert werden.',
        'ackerboden': 'Ackerboden kann hergestellt werden, indem der Boden mit einer Hacke bearbeitet wird.',
        'golderz': 'Golderz erhält man, indem Golderzblöcke mit einer Spitzhacke aus Eisen oder einem hochwertigerem Material abgebaut werden.',
        'andesit': 'Andesit kann mit einer Spitzhacke abgebaut werden, oder es lässt sich craften, indem in der Werkbank Diorit neben Bruchstein platziert wird.',
        'roter farbstoff': 'Roter Farbstoff kann gecraftet werden, indem eine Mohnblume in die Werkbank gelegt wird.',
        'eisenaxt': 'Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein ' +
        'Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.',
        'hellblauer farbstoff': 'Hellblauer Farbstoff kann gecraftet werden, indem im Craftingfeld Lapislazuli neben Knochenmehl platziert wird.',
        'grauer farbstoff': 'Grauer Farbstoff kann gecraftet werden, indem im Craftingfeld Knochenmehl neben einem Tintenbeutel platziert wird.',
        'blau gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'eiserne pferderüstung': 'Eine Pferderüstung kann zufällig in Verliesen, Netherfestungen, bei Schmieden, in Dschungeltempeln, Wüstentempeln und Truhen in Festungen gefunden werden.',
        'rot gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'ziegeltreppe': 'Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.',
        'goldene hose': 'Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.',
        'schwarzeichenzauntor': 'Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.',
        'witherschädel': 'Schädel erhält man, indem man mit einem geladenen Creeper die Kreatur explodieren lässt, deren Schädel man möchte.',
        'spinnenauge': 'Ein Spinnenauge droppt zufällig beim Töten von Spinnen oder Hexen.',
        'magenta gefärbtes glas': 'Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.',
        'braun gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'kürbiskuchen': 'Ein Kürbiskuchen kann gecraftet werden, indem in der Werkbank ein Kürbis in das linke mittlere Feld, Zucker in das Feld ganz in der Mitte und ein Ei in das untere mittlere Feld platziert werden.',
        'schneeball': 'Einen Schneeball erhält man, indem Schnee mit einer Schaufel zerkleinert wird.',
        'jukebox': 'Eine Jukebox wird hergestellt, indem ein Diamant in einer Werkbank im mittleren Feld platziert und von Holzbrettern umgeben wird.',
        'sand': 'Sand erhält man, indem Sandblöcke zerkleinert werden.',
        'toter busch': 'Tote Büsche, auch nur Büsche genannt, werden mit einer Schere erhalten.',
        'ziegelstufe': 'Eine Ziegelstufe kann hergestellt werden, indem in einer Werkbank drei Ziegelstein-Blöcke in einer Reihe platziert werden.',
        'seerosenblatt': 'Seerosenblätter kommen natürlich auf Wasser in Sümpfen oder unterirdischen Seen vor.',
        'lederhose': 'Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.',
        'bemooste bruchsteinmauer': 'Eine Bemooste Bruchsteinmauer wird gecraftet, indem sechs Bemooste Bruchsteine in die beiden unteren Reihen einer Werkbank platziert werden.',
        'schallplatte 11': 'Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.',
        'violett gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'magenta gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'schallplatte mall': 'Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.',
        'tropenholz': 'Alle Holzarten können erhalten werden, indem der entsprechende Baum zerstört wird.',
        'diamantaxt': 'Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein Stock in das Feld ganz in ' +
        'der Mitte und das in der Mitte der unteren Reihe platziert werden.',
        'leere karte': 'Eine Karte kann gecraftet werden, indem ein Kompass in das Feld ganz in der Mitte platziert und dann von acht Blättern Papier umgeben wird.',
        'steindruckplatte': 'Eine Steindruckplatte lässt sich craften, indem zwei glatte Steine horizontal nebeneinander in das Craftingfeld gelegt werden.',
        'falltür': 'Falltüren können entweder mit Holzbrettern oder Eisenbarren gecraftet werden. Um eine Holzfalltür zu craften, werden Holzbretter in alle Felder der beiden unteren Reihen platziert. Um eine Eisenfalltür zu craften, ' +
        'werden Eisenbarren in einem 2x2-Raster in einer Werkbank platziert.',
        'goldstiefel': 'Alle Stiefel lassen sich craften, indem das gewünschte Material im linken mittleren, linken unteren, rechten mittleren und rechten unteren Feld einer Werkbank platziert wird.',
        'schallplatte stall': 'Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.',
        'redstone-kabel': 'Das Redstone-Kabel ist einfach Redstone, das auf dem Boden platziert wird.',
        'kolben': 'Ein Kolben kann gecraftet werden, indem ein Eisenbarren im Feld ganz in der Mitte, Redstone im unteren mittleren Feld, Holzbretter in allen Felder der oberen Reihe und Bruchstein in den übrigen Feldern platziert werden.',
        'weiß gefärbtes glas': 'Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.',
        'antriebslore': 'Eine Antriebslore wird gecraftet, indem ein Ofen in einem Craftingfeld über einer Lore platziert wird.',
        'zucker': 'Zucker kann erhalten werden, indem Zuckerrohr in einer Werkbank platziert wird.',
        'kettenhemd': 'Kettenrüstung kann nur durch den Handel mit einem Dorfbewohner oder einem seltenen Drop von einer Kreatur erhalten werden.',
        'feder': 'Federn können zufällig durch das Töten von Hühnern erhalten werden.',
        'hellblau gefärbtes glas': 'Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.',
        'eichenholzzaun': 'Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.',
        'steinspitzhacke': 'Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in ' +
        'der Mitte und das in der Mitte der unteren Reihe platziert wird.',
        'rosa teppich': 'Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.',
        'monsterspawner': 'Monsterspawner können in Minecraft nur durch Cheats erhalten werden.',
        'goldene karotte': 'Eine Goldene Karotte kann gecraftet werden, indem eine Karotte in das Feld ganz in der Mitte gelegt und dann von acht Goldklumpen umgeben wird.',
        'stock': 'Ein Stock kann gecraftet werden, indem in einem Craftingfeld ein Holzbrett über einem Holzbrett platziert wird.',
    },
};