/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/
module.exports = {
    RECIPE_EN_GB: {
        'move': 'Left stick on playstation. ',
        'sprint': 'X on playstation. ',
        'run': 'X on playstation. ',
        'camera control': 'right stick on playstation. ',
        'camera': 'right stick on playstation. ',
        'rotate camera': 'right stick on playstation. ',
        'rotate': 'right stick on playstation. ',
        'look': 'right stick on playstation. ',
        'switch weapon': 'L 1 on playstation. ',
        'game menu': 'Options on playstation. ',
        'menu': 'Options on playstation. ',
        'switch weapons': 'L 1 on playstation. ',
        'opens menu': 'Options on playstation. ',
        'shoot': 'L 2 on playstation. ',
        'arrow': 'L 2 on playstation. ',
        'weapon': 'L 1 on playstation. ',
        'roll': 'Circle on playstation. ',
        'keep': 'Square on playstation. ',
        'collapse': 'Triangle on playstation. ',
        'hit': 'L 2 on playstation. ',
        'hard hit': 'R 2 on playstation. ',
        'movement': 'Left stick on playstation. ',
        'item': 'Left on d pad on playstation. ',
    },
    RECIPE_EN_US: {
        'move': 'Left stick on playstation. ',
        'sprint': 'X on playstation. ',
        'run': 'X on playstation. ',
        'camera control': 'right stick on playstation. ',
        'camera': 'right stick on playstation. ',
        'rotate camera': 'right stick on playstation. ',
        'rotate': 'right stick on playstation. ',
        'look': 'right stick on playstation. ',
        'switch weapon': 'L 1 on playstation. ',
        'game menu': 'Options on playstation. ',
        'menu': 'Options on playstation. ',
        'switch weapons': 'L 1 on playstation. ',
        'opens menu': 'Options on playstation. ',
        'shoot': 'L 2 on playstation. ',
        'arrow': 'L 2 on playstation. ',
        'weapon': 'L 1 on playstation. ',
        'roll': 'Circle on playstation. ',
        'keep': 'Square on playstation. ',
        'collapse': 'Triangle on playstation. ',
        'hit': 'L 2 on playstation. ',
        'hard hit': 'R 2 on playstation. ',
        'movement': 'Left stick on playstation. ',
        'item': 'Left on d pad on playstation. ',
    },
    RECIPE_DE_DE: {
        'schneegolem': 'Ein Schneegolem kann erschaffen werden, indem ein Kürbis auf zwei auf dem Boden stehende Schneeblöcke gesetzt wird.',
        'quarzsäule': 'Eine Quarzsäule erhält man, indem in Minecraft ein Quarzblock auf einem Quarzblock platziert wird.',
        'feuerwerksrakete': 'Eine Feuerwerksrakete kann gecraftet werden, indem ein Feuerwerksstern in das linke mittlere Feld, ein Blatt Papier in das mittlere Feld und Schwarzpulver in das rechte mittlere Feld der Werkbank gelegt wird. ' +
        'Ähnlich wie bei einem Feuerwerksstern kann einer Feuerwerksrakete in der unteren Reihe zusätzliches Schwarzpulver hinzugefügt werden, um die Dauer der Rakete zu verlängern.',
        'kaninchenragout': 'Kaninchenragout kann gecraftet werden, indem ein Gekochtes Kaninchen in das obere mittlere Feld, eine Karotte in das linke mittlere Feld, eine Ofenkartoffel in das Feld ganz in der Mitte, ' +
        'eine beliebige Pilzart in das rechte mittlere Feld und eine Schüssel in des untere mittlere Feld platziert wird.',
        'kessel': 'Ein Kessel kann hergestellt werden, indem Eisenbarren in alle Felder der Werkbank mit Ausnahme des oberen mittleren Feldes und des Feldes ganz in der Mitte gelegt werden.',
        'steinschaufel': 'Jede Art von Schaufel lässt sich craften, indem auf der Werkbank das gewünschte Material in das obere mittlere Feld gelegt wird und dann Stöcke in die beiden direkt darunter befindlichen Felder platziert werden.',
        'roter teppich': 'Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.',
        'buch und feder': 'Buch und Feder kann gecraftet werden, indem in der Werkbank ein Buch in das linke mittlere Feld, ein Tintenbeutel in das Feld ganz in der Mitte und eine Feder in das untere mittlere Feld platziert werden.',
        'rahmen': 'Ein Rahmen kann gecraftet werden, indem Leder in das Feld ganz in der Mitte platziert und dann von acht Stöcken umgeben wird.',
        'karte': 'Eine Karte kann gecraftet werden, indem ein Kompass in das Feld ganz in der Mitte platziert und dann von acht Blättern Papier umgeben wird.',
        'klebriger Kolben': 'Ein klebriger Kolben kann gecraftet werden, indem ein Schleimball im Craftingfeld über einem Kolben platziert wird.',
        'brot': 'Brot kann gecraftet werden, indem eine Reihe der Werkbank vollständig mit Weizen gefüllt wird.',
        'holzspitzhacke': 'Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in ' +
        'der Mitte und das in der Mitte der unteren Reihe platziert wird.',
        'schere': 'Eine Schere kann gecraftet werden, indem zwei Eisenbarren diagonal zueinander platziert werden.',
        'rohes rindfleisch': 'Rohes Rindfleisch wird beim Tod einer Kuh oder Mooshroom gedroppt.',
        'glatter roter sandstein': 'Glatter roter Sandstein kann gecraftet werden, indem im Craftingfeld vier rote Sandsteinblöcke in einem 2x2-Raster platziert werden.',
        'prismarinkristalle': 'Prismarinkristalle erhält man, indem Wächter und große Wächter besiegt werden.',
        'eichenholzstufe': 'Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.',
        'holzschwert': 'Jede Art von Schwert lässt sich craften, indem auf einer Werkbank das gewünschte Material in das obere mittlere Feld sowie das Feld ganz in der Mitte platziert und dann ein Stock in das darunter befindliche Feld gelegt wird.',
        'treppe': 'Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.',
        'tropenholzzaun': 'Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.',
        'aktivierungsschiene': 'Eine Aktivierungsschiene kann gecraftet werden, indem eine Redstone-Fackel in das Feld ganz in der Mitte, Stöcke darüber und darunter und dann sechs Eisenbarren in den übrigen Feldern der Werkbank platziert werden.',
        'ackerboden': 'Ackerboden kann hergestellt werden, indem der Boden mit einer Hacke bearbeitet wird.',
        'golderz': 'Golderz erhält man, indem Golderzblöcke mit einer Spitzhacke aus Eisen oder einem hochwertigerem Material abgebaut werden.',
        'andesit': 'Andesit kann mit einer Spitzhacke abgebaut werden, oder es lässt sich craften, indem in der Werkbank Diorit neben Bruchstein platziert wird.',
        'roter farbstoff': 'Roter Farbstoff kann gecraftet werden, indem eine Mohnblume in die Werkbank gelegt wird.',
        'eisenaxt': 'Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein ' +
        'Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.',
        'hellblauer farbstoff': 'Hellblauer Farbstoff kann gecraftet werden, indem im Craftingfeld Lapislazuli neben Knochenmehl platziert wird.',
        'grauer farbstoff': 'Grauer Farbstoff kann gecraftet werden, indem im Craftingfeld Knochenmehl neben einem Tintenbeutel platziert wird.',
        'blau gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'eiserne pferderüstung': 'Eine Pferderüstung kann zufällig in Verliesen, Netherfestungen, bei Schmieden, in Dschungeltempeln, Wüstentempeln und Truhen in Festungen gefunden werden.',
        'rot gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'ziegeltreppe': 'Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.',
        'goldene hose': 'Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.',
        'schwarzeichenzauntor': 'Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.',
        'witherschädel': 'Schädel erhält man, indem man mit einem geladenen Creeper die Kreatur explodieren lässt, deren Schädel man möchte.',
        'spinnenauge': 'Ein Spinnenauge droppt zufällig beim Töten von Spinnen oder Hexen.',
        'magenta gefärbtes glas': 'Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.',
        'braun gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'kürbiskuchen': 'Ein Kürbiskuchen kann gecraftet werden, indem in der Werkbank ein Kürbis in das linke mittlere Feld, Zucker in das Feld ganz in der Mitte und ein Ei in das untere mittlere Feld platziert werden.',
        'schneeball': 'Einen Schneeball erhält man, indem Schnee mit einer Schaufel zerkleinert wird.',
        'jukebox': 'Eine Jukebox wird hergestellt, indem ein Diamant in einer Werkbank im mittleren Feld platziert und von Holzbrettern umgeben wird.',
        'sand': 'Sand erhält man, indem Sandblöcke zerkleinert werden.',
        'toter busch': 'Tote Büsche, auch nur Büsche genannt, werden mit einer Schere erhalten.',
        'ziegelstufe': 'Eine Ziegelstufe kann hergestellt werden, indem in einer Werkbank drei Ziegelstein-Blöcke in einer Reihe platziert werden.',
        'seerosenblatt': 'Seerosenblätter kommen natürlich auf Wasser in Sümpfen oder unterirdischen Seen vor.',
        'lederhose': 'Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.',
        'bemooste bruchsteinmauer': 'Eine Bemooste Bruchsteinmauer wird gecraftet, indem sechs Bemooste Bruchsteine in die beiden unteren Reihen einer Werkbank platziert werden.',
        'schallplatte 11': 'Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.',
        'violett gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'magenta gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
        'schallplatte mall': 'Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.',
        'tropenholz': 'Alle Holzarten können erhalten werden, indem der entsprechende Baum zerstört wird.',
        'diamantaxt': 'Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein Stock in das Feld ganz in ' +
        'der Mitte und das in der Mitte der unteren Reihe platziert werden.',
        'leere karte': 'Eine Karte kann gecraftet werden, indem ein Kompass in das Feld ganz in der Mitte platziert und dann von acht Blättern Papier umgeben wird.',
        'steindruckplatte': 'Eine Steindruckplatte lässt sich craften, indem zwei glatte Steine horizontal nebeneinander in das Craftingfeld gelegt werden.',
        'falltür': 'Falltüren können entweder mit Holzbrettern oder Eisenbarren gecraftet werden. Um eine Holzfalltür zu craften, werden Holzbretter in alle Felder der beiden unteren Reihen platziert. Um eine Eisenfalltür zu craften, ' +
        'werden Eisenbarren in einem 2x2-Raster in einer Werkbank platziert.',
        'goldstiefel': 'Alle Stiefel lassen sich craften, indem das gewünschte Material im linken mittleren, linken unteren, rechten mittleren und rechten unteren Feld einer Werkbank platziert wird.',
        'schallplatte stall': 'Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.',
        'redstone-kabel': 'Das Redstone-Kabel ist einfach Redstone, das auf dem Boden platziert wird.',
        'kolben': 'Ein Kolben kann gecraftet werden, indem ein Eisenbarren im Feld ganz in der Mitte, Redstone im unteren mittleren Feld, Holzbretter in allen Felder der oberen Reihe und Bruchstein in den übrigen Feldern platziert werden.',
        'weiß gefärbtes glas': 'Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.',
        'antriebslore': 'Eine Antriebslore wird gecraftet, indem ein Ofen in einem Craftingfeld über einer Lore platziert wird.',
        'zucker': 'Zucker kann erhalten werden, indem Zuckerrohr in einer Werkbank platziert wird.',
        'kettenhemd': 'Kettenrüstung kann nur durch den Handel mit einem Dorfbewohner oder einem seltenen Drop von einer Kreatur erhalten werden.',
        'feder': 'Federn können zufällig durch das Töten von Hühnern erhalten werden.',
        'hellblau gefärbtes glas': 'Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.',
        'eichenholzzaun': 'Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.',
        'steinspitzhacke': 'Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in ' +
        'der Mitte und das in der Mitte der unteren Reihe platziert wird.',
        'rosa teppich': 'Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.',
        'monsterspawner': 'Monsterspawner können in Minecraft nur durch Cheats erhalten werden.',
        'goldene karotte': 'Eine Goldene Karotte kann gecraftet werden, indem eine Karotte in das Feld ganz in der Mitte gelegt und dann von acht Goldklumpen umgeben wird.',
        'stock': 'Ein Stock kann gecraftet werden, indem in einem Craftingfeld ein Holzbrett über einem Holzbrett platziert wird.',
    },
};